### ISSUE TITLE
Add Unit Tests for Sort Algorithms

### ISSUE THREAD

**Issue by MiroslavKolosnjaji** [MiroslavKolosnjaji/algorithms-by-example#9]
### Tasks:

- [x] Implement unit tests for ```BubbleSort``` class.
- [x] Implement unit tests for ```BucketSort``` class.
- [x] Implement unit tests for ```CountingSort``` class.
- [x] Implement unit tests for ```InsertionSort``` class.
- [x] Implement unit tests for ```MergeSort``` class.
- [x] Implement unit tests for ```QuickSort``` class.
- [x] Implement unit tests for ```SelectionSort``` class.
